name: Auto PR Feature to Main

on:
  push:
    branches:
      - 'feature/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request-main:
    name: 'Create Pull Request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create PR to Main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create PR if it not exists
          PR_EXISTS=$(gh pr list --head "${{ github.ref_name }}" --base main --json number -q '.[0].number')
          
          if [ -z "$PR_EXISTS" ]; then
            gh pr create \
              --head "${{ github.ref_name }}" \
              --base main \
              --title "Automated PR ${{ github.ref_name }} into Main" \
              --body ""
          else
            echo "PR already exists for this branch. Skipping."
          fi